# Generated by Django 3.1 on 2020-08-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='abstract')),
                ('thumbnail', models.ImageField(upload_to='abstract')),
                ('thumbnailWidth', models.IntegerField()),
                ('thumbnailHeight', models.IntegerField()),
            ],
        ),
    ]
