# Generated by Django 3.1 on 2020-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='scenic')),
                ('thumbnail', models.ImageField(upload_to='scenic')),
                ('thumbnailWidth', models.IntegerField()),
                ('thumbnailHeight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='street')),
                ('thumbnail', models.ImageField(upload_to='street')),
                ('thumbnailWidth', models.IntegerField()),
                ('thumbnailHeight', models.IntegerField()),
            ],
        ),
    ]
