# Generated by Django 3.1 on 2020-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_scenic_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='margin',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='scenic',
            name='margin',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='street',
            name='margin',
            field=models.IntegerField(default=2),
        ),
    ]
